(source gnu)
(source melpa)

;; cask
(depends-on "cask")

;; git
(depends-on "magit")
(depends-on "git-gutter")

;; input method
(depends-on "ddskk")

;; theme
(depends-on "moe-theme")

;; completion
(depends-on "company")
(depends-on "company-math")
(depends-on "company-auctex")

;; Tools
(depends-on "yasnippet")
(depends-on "undo-tree")
(depends-on "rainbow-delimiters")
(depends-on "anzu")
(depends-on "popwin")

;; TeX
(depends-on "auctex")

;; Markdown
(depends-on "markdown-mode")
